language: python

python:
    - 3.6

env:
    - KAFKA_VERSION=2.0.0
    - KAFKA_VERSION=1.1.1
    - KAFKA_VERSION=1.1.0

sudo: false

addons:
  apt:
    packages:
      - libsnappy-dev

cache:
  directories:
    - $HOME/.cache/pip
    - servers/

before_install:
    - ./build_integration.sh

install:
    - pip install tox coveralls
    - pip install .

script:
  - tox -e `if [ "$TRAVIS_PYTHON_VERSION" == "pypy" ]; then echo pypy; else echo py${TRAVIS_PYTHON_VERSION/./}; fi`

after_success:
  - coveralls
